"""add_sedes_and_sede_id_to_simulacros

Revision ID: 076ac924e65e
Revises: e6a9babcdf7f
Create Date: 2026-06-26 09:31:27.096089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076ac924e65e'
down_revision = 'e6a9babcdf7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sedes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=False),
        sa.Column('direccion', sa.String(length=255), nullable=True),
        sa.Column('telefono', sa.String(length=20), nullable=True),
        sa.Column('activo', sa.Boolean(), nullable=True),
        sa.Column('institucion_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.add_column('simulacros', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'simulacros', 'sedes', ['sede_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'simulacros', type_='foreignkey')
    op.drop_column('simulacros', 'sede_id')
    op.drop_table('sedes')
    # ### end Alembic commands ###
