"""remove cupos_maximos and add sede_id to simulacros

Revision ID: 44af271c7968
Revises: 4d633e0a11b0
Create Date: 2026-06-26 20:06:11.142125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44af271c7968'
down_revision = '4d633e0a11b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulacros', 'cupos_maximos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulacros', sa.Column('cupos_maximos', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
