"""initial_schema

Revision ID: e6a9babcdf7f
Revises: 
Create Date: 2026-06-26 04:32:37.179293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector  # noqa: F401

# revision identifiers, used by Alembic.
revision = 'e6a9babcdf7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo_dane', sa.String(length=12), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email_contacto', sa.String(length=255), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('nombre_rector', sa.String(length=255), nullable=False),
    sa.Column('email_rector', sa.String(length=255), nullable=False),
    sa.Column('telefono_rector', sa.String(length=20), nullable=True),
    sa.Column('wolfram_app_id', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instituciones_codigo_dane'), 'instituciones', ['codigo_dane'], unique=True)
    op.create_index(op.f('ix_instituciones_id'), 'instituciones', ['id'], unique=False)
    op.create_index(op.f('ix_instituciones_nit'), 'instituciones', ['nit'], unique=True)
    op.create_table('modelos_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_visible', sa.String(length=255), nullable=False),
    sa.Column('modelo_codigo', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('es_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_ia_id'), 'modelos_ia', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('conversaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('ultimo_mensaje_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_id'), 'conversaciones', ['id'], unique=False)
    op.create_index(op.f('ix_conversaciones_institucion_id'), 'conversaciones', ['institucion_id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_table('simulacros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('cupos_maximos', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_disponible_desde', sa.Date(), nullable=True),
    sa.Column('fecha_disponible_hasta', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulacros_id'), 'simulacros', ['id'], unique=False)
    op.create_table('preguntas_usadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=True),
    sa.Column('componente', sa.String(length=255), nullable=True),
    sa.Column('competencia', sa.String(length=255), nullable=True),
    sa.Column('version_simulacro', sa.String(length=50), nullable=True),
    sa.Column('simulacro_id', sa.Integer(), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacro_id'], ['simulacros.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preguntas_usadas_area', 'preguntas_usadas', ['area'], unique=False)
    op.create_index('idx_preguntas_usadas_institucion', 'preguntas_usadas', ['institucion_id'], unique=False)
    op.create_index('idx_preguntas_usadas_institucion_area', 'preguntas_usadas', ['institucion_id', 'area'], unique=False)
    op.create_index('idx_preguntas_usadas_version', 'preguntas_usadas', ['version_simulacro'], unique=False)
    op.create_index(op.f('ix_preguntas_usadas_hash_contenido'), 'preguntas_usadas', ['hash_contenido'], unique=False)
    op.create_index(op.f('ix_preguntas_usadas_id'), 'preguntas_usadas', ['id'], unique=False)
    op.create_table('reportes_grupales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacro_id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('informe_contenido', sa.Text(), nullable=False),
    sa.Column('estadisticas_agregadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.ForeignKeyConstraint(['simulacro_id'], ['simulacros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulacro_id', 'institucion_id', name='uq_reporte_grupal_simulacro')
    )
    op.create_index(op.f('ix_reportes_grupales_id'), 'reportes_grupales', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_numero_documento'), 'usuarios', ['numero_documento'], unique=True)
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('metadata_msg', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imagen_adjunto', sa.Text(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_id'), 'mensajes', ['id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('leida_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_usuario_id', sa.Integer(), nullable=True),
    sa.Column('event_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'event_key', name='uq_notificaciones_usuario_event_key')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_institucion_id'), 'notificaciones', ['institucion_id'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index('ix_notificaciones_usuario_created_at', 'notificaciones', ['usuario_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_index('ix_notificaciones_usuario_leida_created_at', 'notificaciones', ['usuario_id', 'leida', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('respuestas_estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacro_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('respuestas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('respuestas_detalladas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_correctas', sa.Integer(), nullable=True),
    sa.Column('total_incorrectas', sa.Integer(), nullable=True),
    sa.Column('puntaje_total', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tiempo_empleado', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notificado', sa.Boolean(), nullable=True),
    sa.Column('informe_generado', sa.Boolean(), nullable=True),
    sa.Column('informe_url', sa.Text(), nullable=True),
    sa.Column('analisis_ia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fraude', sa.Boolean(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_by', sa.Integer(), nullable=True),
    sa.Column('reset_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.ForeignKeyConstraint(['simulacro_id'], ['simulacros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_estudiantes_id'), 'respuestas_estudiantes', ['id'], unique=False)
    op.create_table('review_preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacro_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_numero', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('revision', sa.Text(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulacro_id'], ['simulacros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_preguntas_id'), 'review_preguntas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_preguntas_id'), table_name='review_preguntas')
    op.drop_table('review_preguntas')
    op.drop_index(op.f('ix_respuestas_estudiantes_id'), table_name='respuestas_estudiantes')
    op.drop_table('respuestas_estudiantes')
    op.drop_index('ix_notificaciones_usuario_leida_created_at', table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index('ix_notificaciones_usuario_created_at', table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_institucion_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_mensajes_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_usuarios_numero_documento'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_reportes_grupales_id'), table_name='reportes_grupales')
    op.drop_table('reportes_grupales')
    op.drop_index(op.f('ix_preguntas_usadas_id'), table_name='preguntas_usadas')
    op.drop_index(op.f('ix_preguntas_usadas_hash_contenido'), table_name='preguntas_usadas')
    op.drop_index('idx_preguntas_usadas_version', table_name='preguntas_usadas')
    op.drop_index('idx_preguntas_usadas_institucion_area', table_name='preguntas_usadas')
    op.drop_index('idx_preguntas_usadas_institucion', table_name='preguntas_usadas')
    op.drop_index('idx_preguntas_usadas_area', table_name='preguntas_usadas')
    op.drop_table('preguntas_usadas')
    op.drop_index(op.f('ix_simulacros_id'), table_name='simulacros')
    op.drop_table('simulacros')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_conversaciones_institucion_id'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_id'), table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_modelos_ia_id'), table_name='modelos_ia')
    op.drop_table('modelos_ia')
    op.drop_index(op.f('ix_instituciones_nit'), table_name='instituciones')
    op.drop_index(op.f('ix_instituciones_id'), table_name='instituciones')
    op.drop_index(op.f('ix_instituciones_codigo_dane'), table_name='instituciones')
    op.drop_table('instituciones')
    # ### end Alembic commands ###
